# Generated by Django 5.1 on 2024-08-23 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urls',
            name='number',
            field=models.IntegerField(null=True),
        ),
    ]
